"""Constants, configuration, and data structures for the AIPCC linter."""

import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

# ============================================================================
# CONSTANTS AND CONFIGURATION
# ============================================================================

POLICY_DOC_URL = "https://docs.google.com/document/d/1TAicyqGKKELzaYL4o-Plz2s7tFUhOctZFzHErMQSc8c"
POLICY_MESSAGE = f"See {POLICY_DOC_URL} for AIPCC Commit and Merge Request Guidelines."

# Bot usernames that are exempt from linting
BOT_NAMES = ["platform-engineering-bot", "aipcc-cicd-bot"]

# Minimum description length after Jira ticket/INTERNAL
MIN_TITLE_DESCRIPTION_LENGTH = 10
MIN_TITLE_DESCRIPTION_WORDS = 3

# File extensions for tool-generated files exempt from newline-at-EOF check.
# These are not null-byte binary, so is_binary_file() won't skip them, but
# common tools that produce them do not add trailing newlines.
TOOL_GENERATED_EXTENSIONS = {
    ".svg",    # XML-based vector graphics, tool-generated
    ".patch",  # Generated by git format-patch or diff tools
    ".diff",   # Generated by git diff or patch tools
    ".pem",    # PEM-encoded certificates/keys
    ".crt",    # X.509 certificates
    ".pub",    # Public key files
    ".key",    # Private key files
    ".lock",   # Dependency lock files (npm, uv, poetry, Gemfile, etc.)
}

# Filename prefix patterns for tool-generated files (matched against basename).
TOOL_GENERATED_FILENAME_PATTERNS = (
    "RPM-GPG-KEY-",  # ASCII-armored GPG keys
)

# Linterignore file search paths (in priority order)
LINTERIGNORE_PATHS = [
    lambda: Path(os.environ.get("HOME", "/home/linter")) / ".config/linterignore",
    lambda: Path("config/linterignore"),
    lambda: Path(".linterignore"),
]

# Compiled regex patterns
# Jira pattern: 2+ uppercase letters, dash, 1+ digits (e.g., RHELAI-1234, AB-1)
JIRA_PATTERN = re.compile(r"(([A-Z]{2,})-(\d+))", flags=re.MULTILINE)
JIRA_INTERNAL_PATTERN = re.compile(r"INTERNAL", flags=re.MULTILINE)
SIGNED_OFF_BY_PATTERN = re.compile(r"Signed-off-by: ", flags=re.MULTILINE)
# Revert pattern: matches GitLab auto-generated revert titles
REVERT_PATTERN = re.compile(r'^Revert "(.+)"$')
# Pattern matching GitLab's default issue-closing keywords followed by Jira issue IDs.
# Mirrors the trigger-word portion of GitLab's ISSUE_CLOSING_REGEX. When a closing
# keyword + Jira ID appears in an MR title, description, or commit message, GitLab
# auto-transitions that Jira issue on merge.
# Ref: https://docs.gitlab.com/user/project/issues/managing_issues/#default-closing-pattern
#
# Supports: "Closes PROJ-123", "Fixes: PROJ-1, PROJ-2", "Resolves PROJ-1 and PROJ-2"
# Uses space-only matching (not \s) to prevent false positives across newline boundaries
# when scanning aggregated MR text.
#
# Note: this pattern is intentionally a superset of GitLab's Jira ID handling.
# GitLab's closing regex likely only captures the first Jira ID in a comma-separated
# list (the separator logic sits in the native-issue branch, not the Jira branch).
# We match all IDs in the list to err on the side of caution - better to warn about
# an Epic that might not be auto-closed than to miss one that would be.
CLOSING_PHRASE_PATTERN = re.compile(
    r'\b(?:clos(?:e[sd]?|ing)|fix(?:e[sd]|ing)?|resolv(?:e[sd]?|ing)|implement(?:s|ed|ing)?)'
    r':? +'
    r'('
    r'[A-Z][A-Z0-9_]+-\d+'
    r'(?:'
    r'(?: *, *(?:and +)?| +and +)'
    r'[A-Z][A-Z0-9_]+-\d+'
    r')*'
    r')',
    re.IGNORECASE
)
# Extract individual Jira-style issue IDs from a closing phrase match
JIRA_ID_EXTRACT_PATTERN = re.compile(r'[A-Z][A-Z0-9_]+-\d+', re.IGNORECASE)

# Protected issue type check configuration
# Only AIPCC tickets are checked; add more keys here to extend coverage.
# Values must be UPPERCASE (compared against uppercased Jira IDs).
ISSUE_TYPE_CHECK_PROJECT_KEYS = {'AIPCC'}
# Add more types here to extend protection (e.g. 'initiative').
# Values must be lowercase (compared against lowercased API responses).
PROTECTED_ISSUE_TYPES = {'epic'}
SKIP_ISSUE_TYPE_CHECK_LABEL = 'skip-issue-type-check'

# ============================================================================
# DATA STRUCTURES
# ============================================================================

@dataclass
class CommitInfo:
    """Information about a git commit."""
    commit_id: str
    title: str
    body: str


@dataclass
class MergeRequestInfo:
    """Information about a GitLab merge request."""
    iid: str
    title: str
    description: Optional[str]
    author: Optional[str]


@dataclass
class GitLabConfig:
    """GitLab API configuration from environment variables."""
    project_id: Optional[str]
    mr_iid: Optional[str]
    api_url: Optional[str]
    api_token: Optional[str]
    base_sha: str

    @classmethod
    def from_environment(cls) -> "GitLabConfig":
        """Create configuration from environment variables.

        For base_sha, checks in order:
        1. CI_MERGE_REQUEST_DIFF_BASE_SHA (GitLab CI)
        2. LINT_BASE_BRANCH (local testing override)
        3. "main" (default)
        """
        base_sha = (
            os.getenv("CI_MERGE_REQUEST_DIFF_BASE_SHA") or
            os.getenv("LINT_BASE_BRANCH") or
            "main"
        )

        return cls(
            project_id=os.getenv("CI_PROJECT_ID"),
            mr_iid=os.getenv("CI_MERGE_REQUEST_IID"),
            api_url=os.getenv("CI_API_V4_URL"),
            api_token=os.getenv("GITLAB_API_TOKEN"),
            base_sha=base_sha,
        )


@dataclass
class JiraConfig:
    """Jira API configuration from environment variables."""
    site_url: Optional[str]
    username: Optional[str]
    api_token: Optional[str]

    @property
    def is_configured(self) -> bool:
        """Check if Jira credentials are configured."""
        return bool(self.site_url and self.username and self.api_token)

    @classmethod
    def from_environment(cls) -> "JiraConfig":
        """Create configuration from environment variables."""
        return cls(
            site_url=os.getenv("JIRA_URL", "https://redhat.atlassian.net").rstrip("/"),
            username=os.getenv("JIRA_USERNAME"),
            api_token=os.getenv("JIRA_API_TOKEN"),
        )


@dataclass
class ValidationResult:
    """Result of a validation operation."""
    success: bool
    error_message: Optional[str] = None

    @classmethod
    def ok(cls) -> "ValidationResult":
        """Create a successful validation result."""
        return cls(success=True)

    @classmethod
    def fail(cls, message: str) -> "ValidationResult":
        """Create a failed validation result."""
        return cls(success=False, error_message=message)
