"""Commit validation functions for the AIPCC linter."""

from typing import List

from config import CommitInfo, POLICY_MESSAGE, ValidationResult, logger
from git.commands import get_commit_modified_files
from git.merge_detection import should_skip_commit_validation
from validators.files import find_linterignore_file, read_linterignore_file, expand_directory_patterns, validate_files_newline_at_eof
from validators.title import has_internal_keyword, validate_title_format, contains_signed_off_by


def validate_commit_title(commit: CommitInfo) -> ValidationResult:
    """
    Validate that commit title follows strict formatting rules.

    Args:
        commit: Commit information

    Returns:
        ValidationResult
    """
    result = validate_title_format(commit.title)
    if not result.success:
        return ValidationResult.fail(
            f"ERROR [COMMIT {commit.commit_id}]: {result.error_message}\n{POLICY_MESSAGE}"
        )
    return ValidationResult.ok()


def validate_commit_signed_off_by(commit: CommitInfo) -> ValidationResult:
    """
    Validate that commit has a Signed-off-by tag.

    Args:
        commit: Commit information

    Returns:
        ValidationResult
    """
    if contains_signed_off_by(commit.body):
        return ValidationResult.ok()

    return ValidationResult.fail(
        f"ERROR [COMMIT {commit.commit_id}]: commit does not contain a Signed-off-by: tag.\n"
        f"{POLICY_MESSAGE}"
    )


def validate_internal_commit_files(commit: CommitInfo) -> ValidationResult:
    """Validate that INTERNAL commit only modifies whitelisted files."""
    linterignore_path = find_linterignore_file()
    patterns = read_linterignore_file(linterignore_path)
    allowed_files = expand_directory_patterns(patterns)

    logger.info(f"Files that can be modified using INTERNAL: {sorted(allowed_files)}")

    modified_files = get_commit_modified_files(commit.commit_id)

    for file_path in modified_files:
        if file_path == "config/linterignore":
            return ValidationResult.fail(
                f"ERROR [COMMIT {commit.commit_id}]: config/linterignore changes cannot be made "
                f"with INTERNAL -- a JIRA must be used to modify this file.\n{POLICY_MESSAGE}"
            )

        if file_path not in allowed_files:
            return ValidationResult.fail(
                f"ERROR [COMMIT {commit.commit_id}]: {file_path} is not in {linterignore_path}"
            )

    return ValidationResult.ok()


def validate_commit(commit: CommitInfo) -> List[str]:
    """
    Validate a single commit against all rules.

    Merge commits are automatically skipped as they are generated by GitLab
    and don't follow the same conventions as regular commits.

    This includes both:
    - Regular merge commits (2+ parents)
    - Cherry-picked merge commits (source has 2+ parents)

    Returns:
        List of error messages (empty if all validations pass)
    """
    # Skip merge commits (regular or cherry-picked)
    if should_skip_commit_validation(commit):
        logger.info(f"{commit.commit_id}: Skipping validation (merge commit)")
        return []

    logger.info(f"{commit.commit_id}:\n{commit.body}\n")
    errors = []

    # Validate title format
    result = validate_commit_title(commit)
    if not result.success:
        errors.append(result.error_message)

    if has_internal_keyword(commit.title):
        result = validate_internal_commit_files(commit)
        if not result.success:
            errors.append(result.error_message)

    result = validate_commit_signed_off_by(commit)
    if not result.success:
        errors.append(result.error_message)

    # Validate that text files end with newline
    result = validate_files_newline_at_eof(commit)
    if not result.success:
        errors.append(result.error_message)

    return errors
